layout_spectrum: 0.3329624
color:
  saturation: 0.8344976
  lightness: 0.4961206
  brandStrength: 0.04063863
  brandColors:
    - '#FFFFFF'
    - '#818286'
    - '#ACACAC'
    - '#484443'
    - '#D25A0F'
  rhythmicContrast: 0.7077625
typography_spectrum: 0.7127949
name: New Hope Industries
